### ISSUE TITLE
Jarvis build check doesn't use the right url for the build

### ISSUE THREAD

**Issue by ph** [elastic/jarvis#57]
Should have use this link http://build-eu-1.elasticsearch.org/job/logstash-plugin-input-jdbc_PR/13/ instead.

````
 An error occurred in publish: Jarvis::Command::Publish::CommitHashDontMatch - workdir_sha1: 0aa6235fb24dcc6003d6544f9f52220d45d37f5d, build_sha1: 951a65ba9f5b81caa82480d4b67687a94d0c1e12, check build_url: http://build-eu-00.elastic.co/job/logstash-plugin-input-jdbc-unit/3/
/home/jls/jarvis/lib/jarvis/commands/publish.rb:66:in `block in execute'
/home/jls/jarvis/lib/jarvis/commands/publish.rb:53:in `each'
/home/jls/jarvis/lib/jarvis/commands/publish.rb:53:in `execute'
/home/jls/.rvm/gems/ruby-2.1.2/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
/home/jls/jarvis/lib/jarvis/clamp_delegate.rb:56:in `block in callback'
/home/jls/jarvis/lib/jarvis/mixins/pool_delegate.rb:16:in `call'
/home/jls/jarvis/lib/jarvis/mixins/pool_delegate.rb:16:in `block in pool_execute'
/home/jls/.rvm/gems/ruby-2.1.2/gems/concurrent-ruby-0.9.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:331:in `call'
/home/jls/.rvm/gems/ruby-2.1.2/gems/concurrent-ruby-0.9.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:331:in `run_task'
/home/jls/.rvm/gems/ruby-2.1.2/gems/concurrent-ruby-0.9.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (3 levels) in create_worker'
/home/jls/.rvm/gems/ruby-2.1.2/gems/concurrent-ruby-0.9.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:303:in `loop'
/home/jls/.rvm/gems/ruby-2.1.2/gems/concurrent-ruby-0.9.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:303:in `block (2 levels) in create_worker'
/home/jls/.rvm/gems/ruby-2.1.2/gems/concurrent-ruby-0.9.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:302:in `catch'
/home/jls/.rvm/gems/ruby-2.1.2/gems/concurrent-ruby-0.9.1/lib/concurrent/executor/ruby_thread_pool_executor.rb:302:in `block in create_worker'

Logs from this execution:
Cloning repo
Switching branches

**Comment by ph** [comment]
@untergeek  I found the issue this wasn't a problem with Jarvis itself, he was doing the right thing. The repository didn't contains any hook to jenkins so the merge to the master branch didnt trigger any build. 

So for the bot the build didn't pass and he refuses to publish.
